local t = Def.ActorFrame{
	LoadActor("1")..{
		OnCommand=cmd(x,80;y,60)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,240;y,60)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,400;y,60)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,560;y,60)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,80;y,180)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,240;y,180)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,400;y,180)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,560;y,180)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,80;y,300)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,240;y,300)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,400;y,300)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,560;y,300)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,80;y,420)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,240;y,420)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,400;y,420)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,560;y,420)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,720;y,60)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,880;y,60)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,720;y,180)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,880;y,180)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,720;y,300)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,880;y,300)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,720;y,420)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,880;y,420)
	};
	LoadActor("_particleLoader1.lua")..{
		OnCommand=cmd()
	};
	LoadActor("_particleLoader1.lua")..{
		OnCommand=cmd()
	};
	LoadActor("_particleLoader1.lua")..{
		OnCommand=cmd(x,SCREEN_LEFT;y,SCREEN_CENTER_Y)
	};
	LoadActor("_particleLoader1.lua")..{
		OnCommand=cmd(x,SCREEN_LEFT;y,SCREEN_CENTER_Y)
	};
	LoadActor("_particleLoader1.lua")..{
		OnCommand=cmd(x,SCREEN_BOTTOM;y,SCREEN_BOTTOM)
	};
	LoadActor("_particleLoader1.lua")..{
		OnCommand=cmd(x,SCREEN_BOTTOM;y,SCREEN_BOTTOM)
	};
	LoadActor("_particleLoader1 - copia.lua")..{
		OnCommand=cmd(rotationx,180)
	};
	LoadActor("_particleLoader1 - copia.lua")..{
		OnCommand=cmd(rotationx,180)
	};
	LoadActor("_particleLoader1 - copia.lua")..{
		OnCommand=cmd(x,SCREEN_LEFT;y,SCREEN_CENTER_Y;rotationx,180)
	};
	LoadActor("_particleLoader1 - copia.lua")..{
		OnCommand=cmd(x,SCREEN_LEFT;y,SCREEN_CENTER_Y;rotationx,180)
	};
	LoadActor("_particleLoader1 - copia.lua")..{
		OnCommand=cmd(x,SCREEN_BOTTOM;y,SCREEN_BOTTOM;rotationx,180)
	};
	LoadActor("_particleLoader1 - copia.lua")..{
		OnCommand=cmd(x,SCREEN_BOTTOM;y,SCREEN_BOTTOM;rotationx,180)
	};
};

return t;