local t = Def.ActorFrame{
	LoadActor("DiceSpin")..{
		OnCommand=cmd()
	};
	LoadActor("DiceSpin")..{
		OnCommand=cmd(addx,56*2)
	};
	LoadActor("DiceSpin")..{
		OnCommand=cmd(addx,56*4)
	};
	LoadActor("DiceSpin")..{
		OnCommand=cmd(addx,56*6)
	};
	LoadActor("DiceSpin")..{
		OnCommand=cmd(addx,56*8)
	};
	LoadActor("DiceSpin")..{
		OnCommand=cmd(addx,56*10)
	};
	LoadActor("DiceSpin")..{
		OnCommand=cmd(addx,-56;addy,56)
	};
	LoadActor("DiceSpin")..{
		OnCommand=cmd(addx,56;addy,56)
	};
	LoadActor("DiceSpin")..{
		OnCommand=cmd(addx,56*3;addy,56)
	};
	LoadActor("DiceSpin")..{
		OnCommand=cmd(addx,56*5;addy,56)
	};
	LoadActor("DiceSpin")..{
		OnCommand=cmd(addx,56*7;addy,56)
	};
	LoadActor("DiceSpin")..{
		OnCommand=cmd(addx,56*9;addy,56)
	};
	LoadActor("DiceSpin")..{
		OnCommand=cmd(addx,56*11;addy,56)
	};
};	

return t;