local t = Def.ActorFrame{
	LoadActor("2.png")..{
		OnCommand=cmd(zoom,1.5;x,SCREEN_CENTER_X;y,SCREEN_TOP;linear,1;zoom,0.5;x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y-100;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,0.2;zoom,1.5;x,SCREEN_RIGHT;y,SCREEN_TOP;linear,1;zoom,0.5;x,SCREEN_CENTER_X+70;y,SCREEN_CENTER_Y-70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,0.4;zoom,1.5;x,SCREEN_RIGHT;y,SCREEN_BOTTOM;linear,1;zoom,0.5;x,SCREEN_CENTER_X+70;y,SCREEN_CENTER_Y+70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,0.6;zoom,1.5;x,SCREEN_CENTER_X;y,SCREEN_BOTTOM;linear,1;zoom,0.5;x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y+100;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,0.8;zoom,1.5;x,SCREEN_LEFT;y,SCREEN_BOTTOM;linear,1;zoom,0.5;x,SCREEN_CENTER_X-70;y,SCREEN_CENTER_Y+70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,1;zoom,1.5;x,SCREEN_LEFT;y,SCREEN_TOP;linear,1;zoom,0.5;x,SCREEN_CENTER_X-70;y,SCREEN_CENTER_Y-70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,1.2;zoom,1.5;x,SCREEN_CENTER_X;y,SCREEN_TOP;linear,1;zoom,0.5;x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y-100;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,1.4;zoom,1.5;x,SCREEN_RIGHT;y,SCREEN_TOP;linear,1;zoom,0.5;x,SCREEN_CENTER_X+70;y,SCREEN_CENTER_Y-70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,1.6;zoom,1.5;x,SCREEN_RIGHT;y,SCREEN_BOTTOM;linear,1;zoom,0.5;x,SCREEN_CENTER_X+70;y,SCREEN_CENTER_Y+70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,1.8;zoom,1.5;x,SCREEN_CENTER_X;y,SCREEN_BOTTOM;linear,1;zoom,0.5;x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y+100;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,2;zoom,1.5;x,SCREEN_LEFT;y,SCREEN_BOTTOM;linear,1;zoom,0.5;x,SCREEN_CENTER_X-70;y,SCREEN_CENTER_Y+70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,2.2;zoom,1.5;x,SCREEN_LEFT;y,SCREEN_TOP;linear,1;zoom,0.5;x,SCREEN_CENTER_X-70;y,SCREEN_CENTER_Y-70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,2.4;zoom,1.5;x,SCREEN_CENTER_X;y,SCREEN_TOP;linear,1;zoom,0.5;x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y-100;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,2.6;zoom,1.5;x,SCREEN_RIGHT;y,SCREEN_TOP;linear,1;zoom,0.5;x,SCREEN_CENTER_X+70;y,SCREEN_CENTER_Y-70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,2.8;zoom,1.5;x,SCREEN_RIGHT;y,SCREEN_BOTTOM;linear,1;zoom,0.5;x,SCREEN_CENTER_X+70;y,SCREEN_CENTER_Y+70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,3;zoom,1.5;x,SCREEN_CENTER_X;y,SCREEN_BOTTOM;linear,1;zoom,0.5;x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y+100;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,3.2;zoom,1.5;x,SCREEN_LEFT;y,SCREEN_BOTTOM;linear,1;zoom,0.5;x,SCREEN_CENTER_X-70;y,SCREEN_CENTER_Y+70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,3.4;zoom,1.5;x,SCREEN_LEFT;y,SCREEN_TOP;linear,1;zoom,0.5;x,SCREEN_CENTER_X-70;y,SCREEN_CENTER_Y-70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,3.6;zoom,1.5;x,SCREEN_CENTER_X;y,SCREEN_TOP;linear,1;zoom,0.5;x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y-100;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,3.8;zoom,1.5;x,SCREEN_RIGHT;y,SCREEN_TOP;linear,1;zoom,0.5;x,SCREEN_CENTER_X+70;y,SCREEN_CENTER_Y-70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,4;zoom,1.5;x,SCREEN_RIGHT;y,SCREEN_BOTTOM;linear,1;zoom,0.5;x,SCREEN_CENTER_X+70;y,SCREEN_CENTER_Y+70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,4.2;zoom,1.5;x,SCREEN_CENTER_X;y,SCREEN_BOTTOM;linear,1;zoom,0.5;x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y+100;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,4.4;zoom,1.5;x,SCREEN_LEFT;y,SCREEN_BOTTOM;linear,1;zoom,0.5;x,SCREEN_CENTER_X-70;y,SCREEN_CENTER_Y+70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
	LoadActor("2.png")..{
		OnCommand=cmd(hibernate,4.6;zoom,1.5;x,SCREEN_LEFT;y,SCREEN_TOP;linear,1;zoom,0.5;x,SCREEN_CENTER_X-70;y,SCREEN_CENTER_Y-70;smooth,0.5;zoom,0;smooth,1;effectclock,'beat');
	};
};

return t;