local t = Def.ActorFrame{
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;texcoordvelocity,0.125,0;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
};

return t;