local t = Def.ActorFrame{
	LoadActor("1")..{
		OnCommand=cmd(x,160;y,120)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,480;y,120)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,800;y,120)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,1120;y,120)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,160;y,360)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,480;y,360)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,800;y,360)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,1120;y,360)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,160;y,600)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,480;y,600)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,800;y,600)
	};
	LoadActor("1")..{
		OnCommand=cmd(x,1120;y,600)
	};
	LoadActor("particleLoader1.lua")..{
		OnCommand=cmd(x,SCREEN_TOP;y,0)
	};
	LoadActor("particleLoader1.lua")..{
		OnCommand=cmd(x,SCREEN_TOP;y,0;rotationy,180)
	};
	LoadActor("particleLoader1.lua")..{
		OnCommand=cmd(x,SCREEN_CENTER_X;y,0)
	};
	LoadActor("particleLoader2.lua")..{
		OnCommand=cmd(x,SCREEN_CENTER_X;y,0;rotationy,180)
	};
	LoadActor("particleLoader2.lua")..{
		OnCommand=cmd(x,SCREEN_RIGHT;y,0)
	};
	LoadActor("particleLoader2.lua")..{
		OnCommand=cmd(x,SCREEN_RIGHT;y,0;rotationy,180)
	};
};

return t;