local t = Def.ActorFrame{
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT)
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;bob;effectmagnitude,20,0,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;croptop,0.0625;bob;effectmagnitude,10,0,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;croptop,0.125;bob;effectmagnitude,20,0,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;croptop,0.1875;bob;effectmagnitude,30,0,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;croptop,0.25;bob;effectmagnitude,40,0,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;croptop,0.3125;bob;effectmagnitude,30,0,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;croptop,0.375;bob;effectmagnitude,20,0,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;croptop,0.4375;bob;effectmagnitude,10,0,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;croptop,0.5;bob;effectmagnitude,20,0,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;croptop,0.5625;bob;effectmagnitude,30,0,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;croptop,0.625;bob;effectmagnitude,40,0,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;croptop,0.6875;bob;effectmagnitude,30,0,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;croptop,0.75;bob;effectmagnitude,20,0,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;croptop,0.8125;bob;effectmagnitude,10,0,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;croptop,0.875;bob;effectmagnitude,20,0,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT;fadeleft,0.125;faderight,0.125;croptop,0.9375;bob;effectmagnitude,30,0,0;effectclock,'beat')
	};
};

return t;