return Def.ActorFrame{
	LoseFocusCommand=function(self)
		self:RunCommandsOnChildren(function(child) child:visible(false):finishtweening() end, {})
	end,

	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(2*8)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(2*7)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(2*6)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(2*5)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(2*4)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(2*3)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(2*2)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(2)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:x(0)
			end
	},
}