return Def.ActorFrame{
	LoseFocusCommand=function(self)
		self:RunCommandsOnChildren(function(child) child:visible(false):finishtweening() end, {})
	end,

	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(10*8)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(10*7)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(10*10)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(10*5)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(10*4)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(10*3)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(10*2)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(10)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:x(0)
			end
	},
}