local t = Def.ActorFrame{
	LoadActor("1 (stretch)")..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH,SCREEN_HEIGHT)	
	};
	LoadActor("2")..{
		OnCommand=cmd(x,64;y,64;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,192;y,64;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,320;y,64;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,448;y,64;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,576;y,64;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,704;y,64;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,832;y,64;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,960;y,64;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,64;y,192;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,192;y,192;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,320;y,192;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,448;y,192;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,576;y,192;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,704;y,192;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,832;y,192;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,960;y,192;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,64;y,320;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,192;y,320;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,320;y,320;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,448;y,320;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,576;y,320;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,704;y,320;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,832;y,320;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,960;y,320;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,64;y,448;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,192;y,448;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,320;y,448;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,448;y,448;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,576;y,448;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,704;y,448;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,832;y,448;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,960;y,448;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,64;y,576;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,192;y,576;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,320;y,576;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,448;y,576;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,576;y,576;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,704;y,576;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("2")..{
		OnCommand=cmd(x,832;y,576;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
	LoadActor("3")..{
		OnCommand=cmd(x,960;y,576;pulse;effectmagnitude,0,1,0;effectclock,'beat')
	};
};

return t;