local t = Def.ActorFrame{
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.05;croptop,0.05;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.1;croptop,0.1;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.15;croptop,0.15;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.2;croptop,0.2;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.25;croptop,0.25;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.3;croptop,0.3;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.35;croptop,0.35;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;spin;effectmagnitude,0,0,-45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;spin;effectmagnitude,0,0,45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;spin;effectmagnitude,0,0,-45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.4;croptop,0.4;spin;effectmagnitude,0,0,45;rotationx,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;spin;effectmagnitude,0,0,45;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;spin;effectmagnitude,0,0,-45;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;spin;effectmagnitude,0,0,45;rotationx,180;rotationy,180;effectclock,'beat')
	};
	LoadActor(GAMESTATE:GetCurrentSong():GetBackgroundPath())..{
		OnCommand=cmd(Center;zoomto,SCREEN_WIDTH*2,SCREEN_HEIGHT*2;cropbottom,0.5;cropright,0.5;cropleft,0.45;croptop,0.45;spin;effectmagnitude,0,0,-45;rotationx,180;effectclock,'beat')
	};
};

return t;