return Def.ActorFrame{
	LoseFocusCommand=function(self)
		self:RunCommandsOnChildren(function(child) child:visible(false):finishtweening() end, {})
	end,

	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(5*8)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(5*7)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(5*6)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(5*5)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(5*4)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(5*3)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(5*2)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:hibernate(5)
			end
	},
	LoadActor("CenterBreak")..{
		OnCommand=function(self)
		self:x(0)
			end
	},
}